# Gestures
TARGET_GESTURES_NODE := "/proc/touchpanel/gesture_enable"
TARGET_TAP_TO_WAKE_NODE := "/proc/touchpanel/double_tap_enable"
TARGET_DRAW_V_NODE := "/proc/touchpanel/down_arrow_enable"
TARGET_DRAW_INVERSE_V_NODE := "/proc/touchpanel/up_arrow_enable"
TARGET_DRAW_O_NODE := "/proc/touchpanel/letter_o_enable"
TARGET_DRAW_ARROW_LEFT_NODE := "/proc/touchpanel/left_arrow_enable"
TARGET_DRAW_ARROW_RIGHT_NODE := "/proc/touchpanel/right_arrow_enable"
TARGET_ONE_FINGER_SWIPE_UP_NODE := "/proc/touchpanel/up_swipe_enable"
TARGET_ONE_FINGER_SWIPE_DOWN_NODE := "/proc/touchpanel/down_swipe_enable"
TARGET_ONE_FINGER_SWIPE_LEFT_NODE := "/proc/touchpanel/left_swipe_enable"
TARGET_ONE_FINGER_SWIPE_RIGHT_NODE := "/proc/touchpanel/right_swipe_enable"
TARGET_TWO_FINGER_SWIPE_NODE := "/proc/touchpanel/double_swipe_enable"
